/** Generated by itemis CREATE code generator. */

import com.yakindu.core.IEventDriven;
import com.yakindu.core.IStatemachine;
import com.yakindu.core.ITimed;
import com.yakindu.core.ITimerService;
import java.util.LinkedList;
import java.util.Queue;

public class Microwave implements ITimed, IEventDriven {
	public enum State {
		MICROWAVE_ENMARCHE,
		MICROWAVE_ENMARCHE_ENMARCHE_NORMAL,
		MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE,
		MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_HIGH,
		MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_LOW,
		MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS,
		MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_BOUTONPRESSE,
		MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_DISPLAYTIME,
		MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON,
		MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_CUISSON,
		MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_PRETACUIRE,
		MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED,
		MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHCLEAR,
		MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHFINISHED,
		MICROWAVE_ENMARCHE_ENMARCHE_ATTENTE,
		MICROWAVE_ENMARCHE_ENMARCHE_INIT,
		$NULLSTATE$
	};
	
	private State[] historyVector = new State[5];
	private final State[] stateVector = new State[1];
	
	private ITimerService timerService;
	
	private final boolean[] timeEvents = new boolean[5];
	
	private Queue<Runnable> inEventQueue = new LinkedList<Runnable>();
	private boolean wasCooking;
	
	protected boolean getWasCooking() {
		return wasCooking;
	}
	
	protected void setWasCooking(boolean value) {
		this.wasCooking = value;
	}
	
	
	private long timeLeft;
	
	protected long getTimeLeft() {
		return timeLeft;
	}
	
	protected void setTimeLeft(long value) {
		this.timeLeft = value;
	}
	
	
	private long nbBtnTpsPresses;
	
	protected long getNbBtnTpsPresses() {
		return nbBtnTpsPresses;
	}
	
	protected void setNbBtnTpsPresses(long value) {
		this.nbBtnTpsPresses = value;
	}
	
	
	private boolean isExecuting;
	
	protected boolean getIsExecuting() {
		return isExecuting;
	}
	
	protected void setIsExecuting(boolean value) {
		this.isExecuting = value;
	}
	public Microwave() {
		for (int i = 0; i < 1; i++) {
			stateVector[i] = State.$NULLSTATE$;
		}
		for (int i = 0; i < 5; i++) {
			historyVector[i] = State.$NULLSTATE$;
		}
		
		clearInEvents();
		
		setPower(0l);
		
		setWasCooking(false);
		
		setTimeLeft(0l);
		
		setNbBtnTpsPresses(0l);
		
		isExecuting = false;
	}
	
	public void enter() {
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		if (this.operationCallback == null) {
			throw new IllegalStateException("Operation callback must be set.");
		}
		
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		
		enterSequence_Microwave_default();
		isExecuting = false;
	}
	
	public void exit() {
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		
		exitSequence_Microwave();
		isExecuting = false;
	}
	
	/**
	 * @see IStatemachine#isActive()
	 */
	public boolean isActive() {
		return stateVector[0] != State.$NULLSTATE$;
	}
	
	/** 
	* Always returns 'false' since this state machine can never become final.
	*
	* @see IStatemachine#isFinal()
	*/
	public boolean isFinal() {
		return false;
	}
	private void clearInEvents() {
		high = false;
		low = false;
		digit = false;
		timer = false;
		start = false;
		stop = false;
		open = false;
		close = false;
		timeEvents[0] = false;
		timeEvents[1] = false;
		timeEvents[2] = false;
		timeEvents[3] = false;
		timeEvents[4] = false;
	}
	
	private void microStep() {
		switch (stateVector[0]) {
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_HIGH:
			microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_high_react(-1l);
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_LOW:
			microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_low_react(-1l);
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_BOUTONPRESSE:
			microwave_Enmarche_enmarche_Normal_normal_Temps_temps_boutonPresse_react(-1l);
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_DISPLAYTIME:
			microwave_Enmarche_enmarche_Normal_normal_Temps_temps_displayTime_react(-1l);
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_CUISSON:
			microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson_react(-1l);
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_PRETACUIRE:
			microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_pretacuire_react(-1l);
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHCLEAR:
			microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashClear_react(-1l);
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHFINISHED:
			microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashFinished_react(-1l);
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_ATTENTE:
			microwave_Enmarche_enmarche_attente_react(-1l);
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_INIT:
			microwave_Enmarche_enmarche_Init_react(-1l);
			break;
		default:
			break;
		}
	}
	
	private void runCycle() {
		if (timerService == null) {
			throw new IllegalStateException("Timer service must be set.");
		}
		if (this.operationCallback == null) {
			throw new IllegalStateException("Operation callback must be set.");
		}
		
		
		if (getIsExecuting()) {
			return;
		}
		isExecuting = true;
		
		nextEvent();
		do { 
			microStep();
			
			clearInEvents();
		} while (nextEvent());
		
		isExecuting = false;
	}
	
	protected boolean nextEvent() {
		if(!inEventQueue.isEmpty()) {
			inEventQueue.poll().run();
			return true;
		}
		return false;
	}
	/**
	* Returns true if the given state is currently active otherwise false.
	*/
	public boolean isStateActive(State state) {
	
		switch (state) {
		case MICROWAVE_ENMARCHE:
			return stateVector[0].ordinal() >= State.
					MICROWAVE_ENMARCHE.ordinal()&& stateVector[0].ordinal() <= State.MICROWAVE_ENMARCHE_ENMARCHE_INIT.ordinal();
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL:
			return stateVector[0].ordinal() >= State.
					MICROWAVE_ENMARCHE_ENMARCHE_NORMAL.ordinal()&& stateVector[0].ordinal() <= State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHFINISHED.ordinal();
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE:
			return stateVector[0].ordinal() >= State.
					MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE.ordinal()&& stateVector[0].ordinal() <= State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_LOW.ordinal();
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_HIGH:
			return stateVector[0] == State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_HIGH;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_LOW:
			return stateVector[0] == State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_LOW;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS:
			return stateVector[0].ordinal() >= State.
					MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS.ordinal()&& stateVector[0].ordinal() <= State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_DISPLAYTIME.ordinal();
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_BOUTONPRESSE:
			return stateVector[0] == State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_BOUTONPRESSE;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_DISPLAYTIME:
			return stateVector[0] == State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_DISPLAYTIME;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON:
			return stateVector[0].ordinal() >= State.
					MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON.ordinal()&& stateVector[0].ordinal() <= State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_PRETACUIRE.ordinal();
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_CUISSON:
			return stateVector[0] == State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_CUISSON;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_PRETACUIRE:
			return stateVector[0] == State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_PRETACUIRE;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED:
			return stateVector[0].ordinal() >= State.
					MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED.ordinal()&& stateVector[0].ordinal() <= State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHFINISHED.ordinal();
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHCLEAR:
			return stateVector[0] == State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHCLEAR;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHFINISHED:
			return stateVector[0] == State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHFINISHED;
		case MICROWAVE_ENMARCHE_ENMARCHE_ATTENTE:
			return stateVector[0] == State.MICROWAVE_ENMARCHE_ENMARCHE_ATTENTE;
		case MICROWAVE_ENMARCHE_ENMARCHE_INIT:
			return stateVector[0] == State.MICROWAVE_ENMARCHE_ENMARCHE_INIT;
		default:
			return false;
		}
	}
	
	public void setTimerService(ITimerService timerService) {
		this.timerService = timerService;
	}
	
	public ITimerService getTimerService() {
		return timerService;
	}
	
	public void raiseTimeEvent(int eventID) {
		inEventQueue.add(() -> {
			timeEvents[eventID] = true;
		});
		runCycle();
	}
	
	
	public interface OperationCallback {
	
		public void displayTime(long t);
		
		public void display(String msg);
		
		public void clearDisplay();
		
		public void cook();
		
		public void stopCook();
		
		public void beepOn();
		
		public void beepOff();
		
		public void closeDoor();
		
		public void openDoor();
		
	}
	
	private OperationCallback operationCallback;
	
	public void setOperationCallback(OperationCallback operationCallback) {
		this.operationCallback = operationCallback;
	}
	
	private boolean high;
	
	
	public void raiseHigh() {
		inEventQueue.add(() -> {
			high = true;
		});
		runCycle();
	}
	
	private boolean low;
	
	
	public void raiseLow() {
		inEventQueue.add(() -> {
			low = true;
		});
		runCycle();
	}
	
	private boolean digit;
	
	private long digitValue;
	
	
	public void raiseDigit(final long value) {
		inEventQueue.add(() -> {
			digitValue = value;
			digit = true;
		});
		runCycle();
	}
	protected long getDigitValue() {
		if (! digit ) 
			throw new IllegalStateException("Illegal event value access. Event Digit is not raised!");
		return digitValue;
	}
	
	private boolean timer;
	
	
	public void raiseTimer() {
		inEventQueue.add(() -> {
			timer = true;
		});
		runCycle();
	}
	
	private boolean start;
	
	
	public void raiseStart() {
		inEventQueue.add(() -> {
			start = true;
		});
		runCycle();
	}
	
	private boolean stop;
	
	
	public void raiseStop() {
		inEventQueue.add(() -> {
			stop = true;
		});
		runCycle();
	}
	
	private boolean open;
	
	
	public void raiseOpen() {
		inEventQueue.add(() -> {
			open = true;
		});
		runCycle();
	}
	
	private boolean close;
	
	
	public void raiseClose() {
		inEventQueue.add(() -> {
			close = true;
		});
		runCycle();
	}
	
	private long power;
	
	public long getPower() {
		return power;
	}
	
	public void setPower(long value) {
		this.power = value;
	}
	
	/* Entry action for state 'high'. */
	private void entryAction_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_high() {
		operationCallback.display("High");
		
		setPower(1l);
	}
	
	/* Entry action for state 'low'. */
	private void entryAction_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_low() {
		operationCallback.display("Low");
		
		setPower(2l);
	}
	
	/* Entry action for state 'boutonPresse'. */
	private void entryAction_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_boutonPresse() {
		timerService.setTimer(this, 0, 1l, false);
		
		setTimeLeft(((timeLeft * 10l) + getDigitValue()));
		
		setNbBtnTpsPresses((nbBtnTpsPresses + 1l));
	}
	
	/* Entry action for state 'displayTime'. */
	private void entryAction_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_displayTime() {
		operationCallback.displayTime(getTimeLeft());
	}
	
	/* Entry action for state 'Cuisson'. */
	private void entryAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson() {
		setWasCooking(true);
		
		operationCallback.cook();
	}
	
	/* Entry action for state 'cuisson'. */
	private void entryAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson() {
		timerService.setTimer(this, 1, (1l * 1000l), false);
		
		operationCallback.displayTime(getTimeLeft());
	}
	
	/* Entry action for state 'pretacuire'. */
	private void entryAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_pretacuire() {
		operationCallback.stopCook();
	}
	
	/* Entry action for state 'Finished'. */
	private void entryAction_Microwave_Enmarche_enmarche_Normal_normal_Finished() {
		timerService.setTimer(this, 2, (5l * 1000l), false);
		
		operationCallback.beepOn();
		
		setWasCooking(false);
	}
	
	/* Entry action for state 'flashClear'. */
	private void entryAction_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashClear() {
		timerService.setTimer(this, 3, 500l, false);
		
		operationCallback.clearDisplay();
	}
	
	/* Entry action for state 'flashFinished'. */
	private void entryAction_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashFinished() {
		timerService.setTimer(this, 4, 500l, false);
		
		operationCallback.display("Finished");
	}
	
	/* Entry action for state 'attente'. */
	private void entryAction_Microwave_Enmarche_enmarche_attente() {
		operationCallback.openDoor();
		
		operationCallback.display("Waiting");
	}
	
	/* Entry action for state 'Init'. */
	private void entryAction_Microwave_Enmarche_enmarche_Init() {
		operationCallback.clearDisplay();
		
		operationCallback.closeDoor();
		
		setWasCooking(false);
		
		setTimeLeft(0l);
		
		setNbBtnTpsPresses(0l);
	}
	
	/* Exit action for state 'boutonPresse'. */
	private void exitAction_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_boutonPresse() {
		timerService.unsetTimer(this, 0);
	}
	
	/* Exit action for state 'Cuisson'. */
	private void exitAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson() {
		operationCallback.stopCook();
	}
	
	/* Exit action for state 'cuisson'. */
	private void exitAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson() {
		timerService.unsetTimer(this, 1);
		
		setTimeLeft(getTimeLeft() - 1l);
	}
	
	/* Exit action for state 'pretacuire'. */
	private void exitAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_pretacuire() {
		operationCallback.cook();
	}
	
	/* Exit action for state 'Finished'. */
	private void exitAction_Microwave_Enmarche_enmarche_Normal_normal_Finished() {
		timerService.unsetTimer(this, 2);
		
		operationCallback.beepOff();
	}
	
	/* Exit action for state 'flashClear'. */
	private void exitAction_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashClear() {
		timerService.unsetTimer(this, 3);
	}
	
	/* Exit action for state 'flashFinished'. */
	private void exitAction_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashFinished() {
		timerService.unsetTimer(this, 4);
	}
	
	/* Exit action for state 'attente'. */
	private void exitAction_Microwave_Enmarche_enmarche_attente() {
		operationCallback.closeDoor();
	}
	
	/* 'default' enter sequence for state Enmarche */
	private void enterSequence_Microwave_Enmarche_default() {
		enterSequence_Microwave_Enmarche_enmarche_default();
	}
	
	/* 'default' enter sequence for state Puissance */
	private void enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_default() {
		enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_default();
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state high */
	private void enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_high_default() {
		entryAction_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_high();
		stateVector[0] = State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_HIGH;
		
		historyVector[1] = stateVector[0];
	}
	
	/* 'default' enter sequence for state low */
	private void enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_low_default() {
		entryAction_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_low();
		stateVector[0] = State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_LOW;
		
		historyVector[1] = stateVector[0];
	}
	
	/* 'default' enter sequence for state Temps */
	private void enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_default() {
		enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_default();
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state boutonPresse */
	private void enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_boutonPresse_default() {
		entryAction_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_boutonPresse();
		stateVector[0] = State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_BOUTONPRESSE;
		
		historyVector[2] = stateVector[0];
	}
	
	/* 'default' enter sequence for state displayTime */
	private void enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_displayTime_default() {
		entryAction_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_displayTime();
		stateVector[0] = State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_DISPLAYTIME;
		
		historyVector[2] = stateVector[0];
	}
	
	/* 'default' enter sequence for state Cuisson */
	private void enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_default() {
		entryAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson();
		enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_default();
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state cuisson */
	private void enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson_default() {
		entryAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson();
		stateVector[0] = State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_CUISSON;
		
		historyVector[3] = stateVector[0];
	}
	
	/* 'default' enter sequence for state pretacuire */
	private void enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_pretacuire_default() {
		entryAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_pretacuire();
		stateVector[0] = State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_PRETACUIRE;
		
		historyVector[3] = stateVector[0];
	}
	
	/* 'default' enter sequence for state Finished */
	private void enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_default() {
		entryAction_Microwave_Enmarche_enmarche_Normal_normal_Finished();
		enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_default();
		historyVector[0] = stateVector[0];
	}
	
	/* 'default' enter sequence for state flashClear */
	private void enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashClear_default() {
		entryAction_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashClear();
		stateVector[0] = State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHCLEAR;
		
		historyVector[4] = stateVector[0];
	}
	
	/* 'default' enter sequence for state flashFinished */
	private void enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashFinished_default() {
		entryAction_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashFinished();
		stateVector[0] = State.MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHFINISHED;
		
		historyVector[4] = stateVector[0];
	}
	
	/* 'default' enter sequence for state attente */
	private void enterSequence_Microwave_Enmarche_enmarche_attente_default() {
		entryAction_Microwave_Enmarche_enmarche_attente();
		stateVector[0] = State.MICROWAVE_ENMARCHE_ENMARCHE_ATTENTE;
	}
	
	/* 'default' enter sequence for state Init */
	private void enterSequence_Microwave_Enmarche_enmarche_Init_default() {
		entryAction_Microwave_Enmarche_enmarche_Init();
		stateVector[0] = State.MICROWAVE_ENMARCHE_ENMARCHE_INIT;
	}
	
	/* 'default' enter sequence for region Microwave */
	private void enterSequence_Microwave_default() {
		react_Microwave__entry_Default();
	}
	
	/* 'default' enter sequence for region enmarche */
	private void enterSequence_Microwave_Enmarche_enmarche_default() {
		react_Microwave_Enmarche_enmarche__entry_Default();
	}
	
	/* deep enterSequence with history in child normal */
	private void deepEnterSequence_Microwave_Enmarche_enmarche_Normal_normal() {
		switch (historyVector[0]) {
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_HIGH:
			deepEnterSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_LOW:
			deepEnterSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_BOUTONPRESSE:
			deepEnterSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_DISPLAYTIME:
			deepEnterSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_CUISSON:
			entryAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson();
			deepEnterSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_PRETACUIRE:
			entryAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson();
			deepEnterSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHCLEAR:
			entryAction_Microwave_Enmarche_enmarche_Normal_normal_Finished();
			deepEnterSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHFINISHED:
			entryAction_Microwave_Enmarche_enmarche_Normal_normal_Finished();
			deepEnterSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished();
			break;
		default:
			break;
		}
	}
	
	/* 'default' enter sequence for region puissance */
	private void enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_default() {
		react_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance__entry_Default();
	}
	
	/* deep enterSequence with history in child puissance */
	private void deepEnterSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance() {
		switch (historyVector[1]) {
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_HIGH:
			enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_high_default();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_LOW:
			enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_low_default();
			break;
		default:
			break;
		}
	}
	
	/* 'default' enter sequence for region temps */
	private void enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_default() {
		react_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps__entry_Default();
	}
	
	/* deep enterSequence with history in child temps */
	private void deepEnterSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps() {
		switch (historyVector[2]) {
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_BOUTONPRESSE:
			enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_boutonPresse_default();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_DISPLAYTIME:
			enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_displayTime_default();
			break;
		default:
			break;
		}
	}
	
	/* 'default' enter sequence for region cuisson */
	private void enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_default() {
		react_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson__entry_Default();
	}
	
	/* deep enterSequence with history in child cuisson */
	private void deepEnterSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson() {
		switch (historyVector[3]) {
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_CUISSON:
			enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson_default();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_PRETACUIRE:
			enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_pretacuire_default();
			break;
		default:
			break;
		}
	}
	
	/* 'default' enter sequence for region finished */
	private void enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_default() {
		react_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished__entry_Default();
	}
	
	/* deep enterSequence with history in child finished */
	private void deepEnterSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished() {
		switch (historyVector[4]) {
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHCLEAR:
			enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashClear_default();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHFINISHED:
			enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashFinished_default();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for state Enmarche */
	private void exitSequence_Microwave_Enmarche() {
		exitSequence_Microwave_Enmarche_enmarche();
	}
	
	/* Default exit sequence for state Normal */
	private void exitSequence_Microwave_Enmarche_enmarche_Normal() {
		exitSequence_Microwave_Enmarche_enmarche_Normal_normal();
	}
	
	/* Default exit sequence for state Puissance */
	private void exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance() {
		exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance();
	}
	
	/* Default exit sequence for state high */
	private void exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_high() {
		stateVector[0] = State.$NULLSTATE$;
	}
	
	/* Default exit sequence for state low */
	private void exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_low() {
		stateVector[0] = State.$NULLSTATE$;
	}
	
	/* Default exit sequence for state Temps */
	private void exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps() {
		exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps();
	}
	
	/* Default exit sequence for state boutonPresse */
	private void exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_boutonPresse() {
		stateVector[0] = State.$NULLSTATE$;
		
		exitAction_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_boutonPresse();
	}
	
	/* Default exit sequence for state displayTime */
	private void exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_displayTime() {
		stateVector[0] = State.$NULLSTATE$;
	}
	
	/* Default exit sequence for state Cuisson */
	private void exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson() {
		exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson();
		exitAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson();
	}
	
	/* Default exit sequence for state cuisson */
	private void exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson() {
		stateVector[0] = State.$NULLSTATE$;
		
		exitAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson();
	}
	
	/* Default exit sequence for state pretacuire */
	private void exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_pretacuire() {
		stateVector[0] = State.$NULLSTATE$;
		
		exitAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_pretacuire();
	}
	
	/* Default exit sequence for state flashClear */
	private void exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashClear() {
		stateVector[0] = State.$NULLSTATE$;
		
		exitAction_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashClear();
	}
	
	/* Default exit sequence for state flashFinished */
	private void exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashFinished() {
		stateVector[0] = State.$NULLSTATE$;
		
		exitAction_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashFinished();
	}
	
	/* Default exit sequence for state attente */
	private void exitSequence_Microwave_Enmarche_enmarche_attente() {
		stateVector[0] = State.$NULLSTATE$;
		
		exitAction_Microwave_Enmarche_enmarche_attente();
	}
	
	/* Default exit sequence for state Init */
	private void exitSequence_Microwave_Enmarche_enmarche_Init() {
		stateVector[0] = State.$NULLSTATE$;
	}
	
	/* Default exit sequence for region Microwave */
	private void exitSequence_Microwave() {
		switch (stateVector[0]) {
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_HIGH:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_high();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_LOW:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_low();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_BOUTONPRESSE:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_boutonPresse();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_DISPLAYTIME:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_displayTime();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_CUISSON:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson();
			exitAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_PRETACUIRE:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_pretacuire();
			exitAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHCLEAR:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashClear();
			exitAction_Microwave_Enmarche_enmarche_Normal_normal_Finished();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHFINISHED:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashFinished();
			exitAction_Microwave_Enmarche_enmarche_Normal_normal_Finished();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_ATTENTE:
			exitSequence_Microwave_Enmarche_enmarche_attente();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_INIT:
			exitSequence_Microwave_Enmarche_enmarche_Init();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region enmarche */
	private void exitSequence_Microwave_Enmarche_enmarche() {
		switch (stateVector[0]) {
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_HIGH:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_high();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_LOW:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_low();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_BOUTONPRESSE:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_boutonPresse();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_DISPLAYTIME:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_displayTime();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_CUISSON:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson();
			exitAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_PRETACUIRE:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_pretacuire();
			exitAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHCLEAR:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashClear();
			exitAction_Microwave_Enmarche_enmarche_Normal_normal_Finished();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHFINISHED:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashFinished();
			exitAction_Microwave_Enmarche_enmarche_Normal_normal_Finished();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_ATTENTE:
			exitSequence_Microwave_Enmarche_enmarche_attente();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_INIT:
			exitSequence_Microwave_Enmarche_enmarche_Init();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region normal */
	private void exitSequence_Microwave_Enmarche_enmarche_Normal_normal() {
		switch (stateVector[0]) {
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_HIGH:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_high();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_LOW:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_low();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_BOUTONPRESSE:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_boutonPresse();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_DISPLAYTIME:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_displayTime();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_CUISSON:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson();
			exitAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_PRETACUIRE:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_pretacuire();
			exitAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHCLEAR:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashClear();
			exitAction_Microwave_Enmarche_enmarche_Normal_normal_Finished();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_FINISHED_FINISHED_FLASHFINISHED:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashFinished();
			exitAction_Microwave_Enmarche_enmarche_Normal_normal_Finished();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region puissance */
	private void exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance() {
		switch (stateVector[0]) {
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_HIGH:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_high();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_PUISSANCE_PUISSANCE_LOW:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_low();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region temps */
	private void exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps() {
		switch (stateVector[0]) {
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_BOUTONPRESSE:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_boutonPresse();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_TEMPS_TEMPS_DISPLAYTIME:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_displayTime();
			break;
		default:
			break;
		}
	}
	
	/* Default exit sequence for region cuisson */
	private void exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson() {
		switch (stateVector[0]) {
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_CUISSON:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson();
			break;
		case MICROWAVE_ENMARCHE_ENMARCHE_NORMAL_NORMAL_CUISSON_CUISSON_PRETACUIRE:
			exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_pretacuire();
			break;
		default:
			break;
		}
	}
	
	/* The reactions of state null. */
	private void react_Microwave_Enmarche_enmarche_Normal_normal__choice_0() {
		if (getWasCooking()==true) {
			enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_default();
		} else {
			react_Microwave_Enmarche_enmarche_Normal_normal__entry_Default();
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave__entry_Default() {
		enterSequence_Microwave_Enmarche_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance__entry_Default() {
		enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_high_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps__entry_Default() {
		enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_displayTime_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson__entry_Default() {
		enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_pretacuire_default();
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished__entry_Default() {
		enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashFinished_default();
	}
	
	/* Default react sequence for deep history entry  */
	private void react_Microwave_Enmarche_enmarche_Normal_normal__entry_Default() {
		/* Enter the region with deep history */
		if (historyVector[0] != State.$NULLSTATE$) {
			deepEnterSequence_Microwave_Enmarche_enmarche_Normal_normal();
		} else {
			enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_default();
		}
	}
	
	/* Default react sequence for initial entry  */
	private void react_Microwave_Enmarche_enmarche__entry_Default() {
		enterSequence_Microwave_Enmarche_enmarche_Init_default();
	}
	
	private long react(long transitioned_before) {
		return transitioned_before;
	}
	
	private long microwave_Enmarche_react(long transitioned_before) {
		long transitioned_after = react(transitioned_before);
		
		if (transitioned_after<0l) {
			if (stop) {
				exitSequence_Microwave_Enmarche();
				enterSequence_Microwave_Enmarche_enmarche_Init_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Enmarche_enmarche_Normal_react(long transitioned_before) {
		long transitioned_after = microwave_Enmarche_react(transitioned_before);
		
		if (transitioned_after<0l) {
			if (open) {
				exitSequence_Microwave_Enmarche_enmarche_Normal();
				enterSequence_Microwave_Enmarche_enmarche_attente_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Enmarche_enmarche_Normal_normal_Puissance_react(long transitioned_before) {
		long transitioned_after = microwave_Enmarche_enmarche_Normal_react(transitioned_before);
		
		if (transitioned_after<0l) {
			if (timer) {
				exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance();
				enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_high_react(long transitioned_before) {
		long transitioned_after = microwave_Enmarche_enmarche_Normal_normal_Puissance_react(transitioned_before);
		
		if (transitioned_after<0l) {
			if (low) {
				exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_high();
				enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_low_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_low_react(long transitioned_before) {
		long transitioned_after = microwave_Enmarche_enmarche_Normal_normal_Puissance_react(transitioned_before);
		
		if (transitioned_after<0l) {
			if (high) {
				exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_low();
				enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_high_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Enmarche_enmarche_Normal_normal_Temps_react(long transitioned_before) {
		long transitioned_after = microwave_Enmarche_enmarche_Normal_react(transitioned_before);
		
		if (transitioned_after<0l) {
			if (start) {
				exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps();
				entryAction_Microwave_Enmarche_enmarche_Normal_normal_Cuisson();
				enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson_default();
				historyVector[0] = stateVector[0];
				
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Enmarche_enmarche_Normal_normal_Temps_temps_boutonPresse_react(long transitioned_before) {
		long transitioned_after = microwave_Enmarche_enmarche_Normal_normal_Temps_react(transitioned_before);
		
		if (transitioned_after<0l) {
			if (timeEvents[0]) {
				exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_boutonPresse();
				timeEvents[0] = false;
				enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_displayTime_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Enmarche_enmarche_Normal_normal_Temps_temps_displayTime_react(long transitioned_before) {
		long transitioned_after = microwave_Enmarche_enmarche_Normal_normal_Temps_react(transitioned_before);
		
		if (transitioned_after<0l) {
			if (((digit) && (getNbBtnTpsPresses()<4l))) {
				exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_displayTime();
				enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Temps_temps_boutonPresse_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Enmarche_enmarche_Normal_normal_Cuisson_react(long transitioned_before) {
		long transitioned_after = microwave_Enmarche_enmarche_Normal_react(transitioned_before);
		
		if (transitioned_after<0l) {
			if (getTimeLeft()==0l) {
				exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson();
				enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson_react(long transitioned_before) {
		long transitioned_after = microwave_Enmarche_enmarche_Normal_normal_Cuisson_react(transitioned_before);
		
		if (transitioned_after<0l) {
			if (timeEvents[1]) {
				exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson();
				timeEvents[1] = false;
				enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_pretacuire_react(long transitioned_before) {
		long transitioned_after = microwave_Enmarche_enmarche_Normal_normal_Cuisson_react(transitioned_before);
		
		if (transitioned_after<0l) {
			if (start) {
				exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_pretacuire();
				enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Cuisson_cuisson_cuisson_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Enmarche_enmarche_Normal_normal_Finished_react(long transitioned_before) {
		long transitioned_after = microwave_Enmarche_enmarche_Normal_react(transitioned_before);
		
		if (transitioned_after<0l) {
			if (timeEvents[2]) {
				exitSequence_Microwave_Enmarche_enmarche_Normal();
				timeEvents[2] = false;
				enterSequence_Microwave_Enmarche_enmarche_Init_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashClear_react(long transitioned_before) {
		long transitioned_after = microwave_Enmarche_enmarche_Normal_normal_Finished_react(transitioned_before);
		
		if (transitioned_after<0l) {
			if (timeEvents[3]) {
				exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashClear();
				timeEvents[3] = false;
				enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashFinished_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashFinished_react(long transitioned_before) {
		long transitioned_after = microwave_Enmarche_enmarche_Normal_normal_Finished_react(transitioned_before);
		
		if (transitioned_after<0l) {
			if (timeEvents[4]) {
				exitSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashFinished();
				timeEvents[4] = false;
				enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Finished_finished_flashClear_default();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Enmarche_enmarche_attente_react(long transitioned_before) {
		long transitioned_after = microwave_Enmarche_react(transitioned_before);
		
		if (transitioned_after<0l) {
			if (close) {
				exitSequence_Microwave_Enmarche_enmarche_attente();
				react_Microwave_Enmarche_enmarche_Normal_normal__choice_0();
				transitioned_after = 0l;
			}
		}
		return transitioned_after;
	}
	
	private long microwave_Enmarche_enmarche_Init_react(long transitioned_before) {
		long transitioned_after = microwave_Enmarche_react(transitioned_before);
		
		if (transitioned_after<0l) {
			if (high) {
				exitSequence_Microwave_Enmarche_enmarche_Init();
				enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_high_default();
				historyVector[0] = stateVector[0];
				
				transitioned_after = 0l;
			} else {
				if (low) {
					exitSequence_Microwave_Enmarche_enmarche_Init();
					enterSequence_Microwave_Enmarche_enmarche_Normal_normal_Puissance_puissance_low_default();
					historyVector[0] = stateVector[0];
					
					transitioned_after = 0l;
				}
			}
		}
		return transitioned_after;
	}
	
	/* Can be used by the client code to trigger a run to completion step without raising an event. */
	public void triggerWithoutEvent() {
		runCycle();
	}
}
